spring:
  application:
    name: ExpenseShare

  datasource:
    url: jdbc:postgresql://localhost:5432/expenseShare_db?options=-c%20TimeZone=Asia/Kathmandu
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
